name: Scan docker image

on:
  workflow_call:

permissions:
  contents: read
  id-token: write

env:
  DOCKER_REPOSITORY: losmino13
  SERVICE: mbition
  ENVIRONMENT: dev

jobs:
  scan:
    name: Scan image and report
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      id: login-dh
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker pull latest image
      id: pull-image
      env:
        DOCKER_REPOSITORY: ${{ steps.login-dh.outputs.registry }}
        IMAGE_TAG: "latest"
      run: |
        docker pull $DOCKER_REPOSITORY/$SERVICE:$IMAGE_TAG
        echo "image=$DOCKER_REPOSITORY/$SERVICE:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Run Trivy vulnerability scanner full
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.pull-image.outputs.image }}
        format: 'table'
        scanners: 'vuln,secret,config'
        output: 'trivy-results.md'
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Upload scan results to arifacts
      uses: actions/upload-artifact@v3
      with:
        name: scan-image-report
        path: trivy-results.md
        retention-days: 7

